export const features = [
    {
        "img":"security.png",
        "title":"安全",
        "decs":"所有資料將都被封鎖在主機內部中，沒有主機使用權限的任何人皆無法訪問，且嚴格管控了能訪問主機的職員."
    },
    {
        "img":"cooperate.png",
        "title":"合作",
        "decs":"與多位專業人士與團隊合作共同維護託管服務，並一起研究探討新的技術，推出更多優質優惠服務."
    },
    {
        "img":"firewall.png",
        "title":"抗攻擊",
        "decs":"本團隊使用著商業防火牆保護著整個網路系統的所有網路流量，且限制了所有網路的出入."
    },
    {
        "img":"dollars.png",
        "title":"便宜",
        "decs":"本團隊經過多次決策與討論，將所有主機價格降至大多數學生皆負擔的起的數字."
    },
    {
        "img":"speed.png",
        "title":"快速",
        "decs":"擁有一個Discord社群在線上."
    },
    {
        "img":"tool.png",
        "title":"維護",
        "decs":"隨時進行託管服務的維護與空間清理，讓託管能一直服務下去"
    },
]